#!/bin/bash

# Check the platform.
if [ "$(uname)" != "Darwin" ]; then
	echo "This script is for Mac only."
	exit 1
fi

# Create utility functions.
getfullpath() {
	python -c 'import os,sys;print(os.path.realpath(sys.argv[1]))' "$1"
}
fail() {
	echo -e "\033[0;31m$1\033[0m"
	exit 1
}
cannot() {
	[ $? -eq 0 ] || fail "Cannot $1."
}
usage() {
	echo "usage: $0 [-m manifest-file] [-f front-end-directory] [-b back-end-file]"
	[ "$1" = "-h" -o "$1" = "--help" ] && exit 0 || exit 2
}

# Run the configuration script first.
D=$(dirname "$0")
"$D/configure" - || exit 1

# Start the Developer Rig.
yarn start
